### ISSUE TITLE
Using an absolute $ref to ref a "pre-added" schema makes the server crash

### ISSUE THREAD

**Issue by ahgentil** [fastify/fastify-swagger#252]
## 🐛 Bug Report

When running `fastify.swagger()` after `listen()`, fastify-swagger crashes the server because it's unable to resolve `params: { $ref: 'http://example.com/#/definitions/idParam' }`. Check code.

## To Reproduce

```js
const fastify = require('fastify')({
  logger: true
})

fastify.register(require('fastify-swagger'), { exposeRoute: true })

fastify.addSchema({
  $id: 'http://example.com/',
  definitions: {
    uuid: {
      type: 'string',
      pattern: '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$'
    },
    idParam: {
      type: 'object',
      required: ['id'],
      properties: {
        id: { $ref: '#/definitions/uuid' }
      },
      additionalProperties: false
    }
  }
})

fastify.get('/some-route/:id', {
  schema: {
    params: { $ref: 'http://example.com/#/definitions/idParam' },
  }
}, (req, reply) => { reply.send('OK') })

// Run the server!
fastify.listen(3001, function (err, address) {
  fastify.swagger() // if commented, all is fine!
  if (err) {
    fastify.log.error(err)
    process.exit(1)
  }
  fastify.log.info(`server listening on ${address}`)
})
```

Error:
```
.../node_modules/fastify-swagger/dynamic.js:381
  if (jsonSchema.type && jsonSchema.properties) {
                 ^

TypeError: Cannot read property 'type' of undefined
    at localRefResolve (.../node_modules/fastify-swagger/dynamic.js:381:18)
    at localRefResolve (.../node_modules/fastify-swagger/dynamic.js:395:12)
(...)
```
## Expected behavior

fastify-swagger to be able to handle the given $ref and to not crash the server.

## Your Environment

- *node version*: 12
- *fastify version*: >=2.0.0
- *os*: Mac
- *any other relevant information*

**Comment by Eomm** [comment]
I just released the fix, you need to reinstall fastify-swagger to get the update.
`npm ls json-schema-resolver` must be at 1.2.1

If you would like to add a test to this repo too, it would be great!

**Comment by ahgentil** [comment]
Thank you 👍 
I'll give it a try tomorrow. About the test, I'll see if I find some time.

**Comment by shimaore** [comment]
I'm confused because I would assume this is fixed as of `fastify-swagger` 3.3.0 but the problem can still be reproduced (using `json-schema-resolver` 1.2.2).

**Comment by ahgentil** [comment]
$refs still don't working properly in the "validation" part of the schema (but the "response/serialisation" part seems ok).

I have something like:
```
 { schema: { params: { $ref: 'http://example.com/plugin1/#/definitions/item1IdParam' } } }
```

And it crashes the server:
```
.../node_modules/fastify-swagger/dynamic.js:394
  const localReference = jsonSchema.$ref.split('/')[2]
                                         ^

TypeError: Cannot read property 'split' of undefined
    at localRefResolve (.../node_modules/fastify-swagger/dynamic.js:394:42)
    at localRefResolve (.../node_modules/fastify-swagger/dynamic.js:395:10)
    at plainJsonObjectToSwagger2 (.../node_modules/fastify-swagger/dynamic.js:329:15)
```

I think this change "didn't help" regarding the crash:
https://github.com/fastify/fastify-swagger/commit/adf0c95c3280fd3a0fae7ceb7c1343f164d02219#diff-3803a4142e90f0f59977727226f37112d7b946ccfeca5b47455aee1ae6dee97bL398-L404

If I revert it I avoid the crash but $ref is not resolved properly:
<img width="638" alt="Screenshot 2020-10-22 at 19 32 13" src="https://user-images.githubusercontent.com/7109418/96908711-4d0c3a00-149d-11eb-8a98-d7214d2d790a.png">
